### ISSUE TITLE
Error in GenericSchemaValidator

### ISSUE THREAD

**Issue by andgur** [miloyip/rapidjson#848] opened 2017-02-09 16:03 UTC
The following code results in a crash
    {
        rapidjson::Document d;
        rapidjson::SchemaDocument   s(d);
        rapidjson::GenericSchemaValidator<rapidjson::SchemaDocument, rapidjson::Document> v(s);
    }

I would suggest changing CreateNullHandler() method like this:
    OutputHandler& CreateNullHandler() {
        return *(nullHandler_ = new OutputHandler);
    }

**Comment by miloyip** [comment] 2017-02-20 02:29
I cannot reproduce this on my machine.
Please state the build environment.

**Comment by andgur** [comment] 2017-02-20 12:05
Visual Studio 2015

**Comment by StilesCrisis** [comment] 2017-02-28 07:03
I can also reproduce this segfault on OS X. (Xcode 8.2.1)

**Comment by StilesCrisis** [comment] 2017-02-28 07:29
Created Pull Request #870 to resolve issue

https://github.com/miloyip/rapidjson/pull/870

**Comment by StilesCrisis** [comment] 2017-02-28 07:34
I added @andgur's code to the unit tests before committing the fix, and Valgrind caught it immediately:
```

3: [ RUN      ] Schema.Issue848
3: ==5217== Conditional jump or move depends on uninitialised value(s)
3: ==5217==    at 0x8140F84: rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>::~GenericDocument() (in /home/travis/build/miloyip/rapidjson/build/bin/unittest)
3: ==5217==    by 0x851FDD7: ??? (in /home/travis/build/miloyip/rapidjson/build/bin/unittest)
3: ==5217== 
3: ==5217== Conditional jump or move depends on uninitialised value(s)
3: ==5217==    at 0x48D202F: free (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
3: ==5217==    by 0x8140FA0: rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>::~GenericDocument() (in /home/travis/build/miloyip/rapidjson/build/bin/unittest)
3: ==5217==    by 0x851FDD7: ??? (in /home/travis/build/miloyip/rapidjson/build/bin/unittest)
3: ==5217== 
3: ==5217== Conditional jump or move depends on uninitialised value(s)
3: ==5217==    at 0x48D1CBF: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
3: ==5217==    by 0x83F7141: rapidjson::GenericSchemaValidator<rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >, rapidjson::CrtAllocator>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>, rapidjson::CrtAllocator>::~GenericSchemaValidator() (in /home/travis/build/miloyip/rapidjson/build/bin/unittest)
3: ==5217==    by 0x851FDD7: ??? (in /home/travis/build/miloyip/rapidjson/build/bin/unittest)
3: ==5217== 
3: [       OK ] Schema.Issue848 (7 ms)

```

**Comment by StilesCrisis** [comment] 2017-03-07 00:21
Pull request has been merged; this issue should be closed.

**Closed** 2017-03-07 01:37 UTC
