### ISSUE TITLE
Internal Compiler Error on IBM AIX XLC compiler

### ISSUE THREAD

**Issue by mengcao** [miloyip/rapidjson#339] opened 2015-05-13 22:12 UTC
version 1.0.1 causes internal compiler error on IBM AIX machines(http://www-03.ibm.com/software/products/en/xlcaix). 

The error message is "Internal compiler error; please contact your Service Representative. "

Below is the code that triggers this issue. 

```
#include <include/rapidjson/document.h>

int main()
{
    const char json[] = "{\"hello\":\"world\",\"t\":true,\"f\":false," \
                        "\"n\":null,\"i\":123,\"pi\":3.1416," \
                        "\"a\":[1,2,3,4]}";
    rapidjson::Document document;
    document.Parse(json);
    return 0;
}
```

**Comment by FrozenGene** [comment] 2015-05-14 06:36
@mengcao Hi, I am a developer of IBM XL C/C++ Compiler. If the program reports Internal Compiler Error(ICE), this should be a problem of IBM XL C/C++ Compiler. 

IBM XLC is a commercial compiler, so if you or your company bought the licence, you or your company should have the contact information of our support team, this is preferred way.

However, if you just use trial version of IBM XL C/C++ Compiler, we also welcome you report this problem. But maybe I need to know more detail about your development environment. 1. which version of XLC you use? 2. which operating system you use? 

Thanks.

Best Regards

Wu Zhao

**Comment by miloyip** [comment] 2015-05-14 06:54
I am really appreciate that @FrozenGene responses so quickly on this.

BTW, I suggest trying to compile the unit tests project. Since in that project, some `.cpp` files only include a minor part of headers in RapidJSON. It may help diagnosing which header potentially causes the problem. But the worst case is the `document.h` generates this problem.

**Comment by mengcao** [comment] 2015-05-14 12:58
Hey @FrozenGene, thanks for the comment. We are running AIX 7.1 and this problem happens for XL C 11, 12 and 13. We are going to report this to IBM shortly but meanwhile, I am wondering if there is any workaround at this moment. Since I noticed that rapidjson used to have build problem on AIX(https://code.google.com/p/rapidjson/issues/detail?id=64), but people managed to get around with it by tweaking the code a little bit. 

@miloyip, thanks for the suggestion, I just noticed that this error only happens when I call any Parse related function, Parse(), Parse<0>(), or ParseInsitu().

**Comment by cyrush** [comment] 2015-10-26 16:33
Hi Folks,

We ran into an internal compiler error like this w/ xlc 12 on BGQ at LLNL and reported this to IBM. Here was our reproducer:
```
#include "rapidjson-master/include/rapidjson/document.h"
#include <iostream>
//-----------------------------------------------------------------------------
int main(int argc, char** argv)
{
    const char json[] = "{ \"hello\" : \"world\" }";
    rapidjson::Document d;
    d.Parse<0>(json);
    std::cout << d["hello"].GetString()  << std::endl;
}
```
IBM was able to resolve the issue for us. 

-Cyrus

**Comment by miloyip** [comment] 2016-02-20 14:43
It seems that it is a compiler issue.
So I close this.

**Closed by miloyip** 2016-02-20 14:43 UTC
Labels: build
