### ISSUE TITLE
RapidJson 1.1.0 with Bond 5.0.0

### ISSUE THREAD

**Issue by yagilofir** [miloyip/rapidjson#792] opened 2016-11-15 12:09 UTC
Hi.
I am working with the SimpleJsonWriter of Bond. So far I used Bond 5.0.0 and RapidJson 1.0.2 and everything worked great.
Recently I have upgraded my RapidJson library to 1.1.0 and since then we are getting compilation errors when trying to serialize simple Bond schemes with the SimpleJsonWriter of Bond.

To make things easier, I created a small project with Bond simple_json example (https://github.com/Microsoft/bond/blob/master/examples/cpp/core/simple_json/simple_json.cpp).
I have included only 3 libraries in this project: Bond 5.0.0, RapidJson 1.1.0 and Boost 1.57.0.

I am getting the same compilation errors in this small project, and the errors come from rapidjson 1.1.0 files.
This is the output when trying to compile the small project:

```
1>------ Build started: Project: CppBondExample, Configuration: Debug Win32 ------
1>  stdafx.cpp
1>  CppBondExample.cpp
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(323): error C2784: 'void rapidjson::PutUnsafe(rapidjson::GenericStringBuffer<Encoding,Allocator> &,Encoding::Ch)' : could not deduce template argument for 'rapidjson::GenericStringBuffer<Encoding,Allocator> &' from 'bond::detail::RapidJsonOutputStream<BufferT>'
1>          with
1>          [
1>              BufferT=bond::OutputBuffer
1>          ]
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(317) : while compiling class template member function 'bool rapidjson::Writer<bond::detail::RapidJsonOutputStream<BufferT>,rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator,0>::WriteDouble(double)'
1>          with
1>          [
1>              BufferT=bond::OutputBuffer
1>          ]
1>          c:\workspace\foundations\externals\windows\bond_5_0_0\include\bond\protocol\simple_json_writer.h(107) : see reference to function template instantiation 'bool rapidjson::Writer<bond::detail::RapidJsonOutputStream<BufferT>,rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator,0>::WriteDouble(double)' being compiled
1>          with
1>          [
1>              BufferT=bond::OutputBuffer
1>          ]
1>          c:\workspace\foundations\externals\windows\bond_5_0_0\include\bond\protocol\simple_json_writer.h(21) : see reference to class template instantiation 'rapidjson::Writer<bond::detail::RapidJsonOutputStream<BufferT>,rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator,0>' being compiled
1>          with
1>          [
1>              BufferT=bond::OutputBuffer
1>          ]
1>          c:\users\oyagil\documents\visual studio 2015\projects\cppbondexample\cppbondexample\cppbondexample.cpp(21) : see reference to class template instantiation 'bond::SimpleJsonWriter<bond::OutputBuffer>' being compiled
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(323): error C2893: Failed to specialize function template 'void rapidjson::PutUnsafe(Stream &,Stream::Ch)'
1>          With the following template arguments:
1>          'Stream=bond::detail::RapidJsonOutputStream<BufferT>'
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(328): error C2784: 'void rapidjson::PutUnsafe(rapidjson::GenericStringBuffer<Encoding,Allocator> &,Encoding::Ch)' : could not deduce template argument for 'rapidjson::GenericStringBuffer<Encoding,Allocator> &' from 'bond::detail::RapidJsonOutputStream<BufferT>'
1>          with
1>          [
1>              BufferT=bond::OutputBuffer
1>          ]
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(328): error C2893: Failed to specialize function template 'void rapidjson::PutUnsafe(Stream &,Stream::Ch)'
1>          With the following template arguments:
1>          'Stream=bond::detail::RapidJsonOutputStream<BufferT>'
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(332): error C2784: 'void rapidjson::PutUnsafe(rapidjson::GenericStringBuffer<Encoding,Allocator> &,Encoding::Ch)' : could not deduce template argument for 'rapidjson::GenericStringBuffer<Encoding,Allocator> &' from 'bond::detail::RapidJsonOutputStream<BufferT>'
1>          with
1>          [
1>              BufferT=bond::OutputBuffer
1>          ]
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(332): error C2893: Failed to specialize function template 'void rapidjson::PutUnsafe(Stream &,Stream::Ch)'
1>          With the following template arguments:
1>          'Stream=bond::detail::RapidJsonOutputStream<BufferT>'
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(333): error C2784: 'void rapidjson::PutUnsafe(rapidjson::GenericStringBuffer<Encoding,Allocator> &,Encoding::Ch)' : could not deduce template argument for 'rapidjson::GenericStringBuffer<Encoding,Allocator> &' from 'bond::detail::RapidJsonOutputStream<BufferT>'
1>          with
1>          [
1>              BufferT=bond::OutputBuffer
1>          ]
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(333): error C2893: Failed to specialize function template 'void rapidjson::PutUnsafe(Stream &,Stream::Ch)'
1>          With the following template arguments:
1>          'Stream=bond::detail::RapidJsonOutputStream<BufferT>'
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(341): error C2784: 'void rapidjson::PutUnsafe(rapidjson::GenericStringBuffer<Encoding,Allocator> &,Encoding::Ch)' : could not deduce template argument for 'rapidjson::GenericStringBuffer<Encoding,Allocator> &' from 'bond::detail::RapidJsonOutputStream<BufferT>'
1>          with
1>          [
1>              BufferT=bond::OutputBuffer
1>          ]
1>          c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\stringbuffer.h(101) : see declaration of 'rapidjson::PutUnsafe'
1>c:\workspace\foundations\externals\windows\rapidjson_1_1_0\include\rapidjson\writer.h(341): error C2893: Failed to specialize function template 'void rapidjson::PutUnsafe(Stream &,Stream::Ch)'
1>          With the following template arguments:
1>          'Stream=bond::detail::RapidJsonOutputStream<BufferT>'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Is this a problem with bond::OutputBuffer or maybe a problem with the rapidjson 1.1.0 library?

Thanks.

P.S:
Also opened an issue for Bond - https://github.com/Microsoft/bond/issues/271 but there is a very good chance the problem is with the new RapidJson version.

**Comment by chwarr** [comment] 2016-11-15 23:28
Bond maintainer here. The problem is with Bond. The `RapidJsonOutputStream` in [rapidjson_helper.h][rjos] does not implement the full [(output) Stream concept][stream-concept] that RapidJSON uses. I have a [pull request][pr-274] against Bond to fix this.

[pr-274]: https://github.com/Microsoft/bond/issues/274
[rjos]: https://github.com/Microsoft/bond/blob/939c298ff6d619dbc0bc9f5ca25c2088de86d83b/cpp/inc/bond/protocol/detail/rapidjson_helper.h#L96
[stream-concept]: http://rapidjson.org/md_doc_stream.html#CustomStream

**Comment by chwarr** [comment] 2016-11-17 17:42
Fix has been merged into Bond's master branch.

**Closed** 2016-11-20 02:08 UTC
