### ISSUE TITLE
How do you resolve kParseErrorDocumentRootNotSingular error?

### ISSUE THREAD

**Issue by xmarklabs** [miloyip/rapidjson#346] opened 2015-05-29 06:16 UTC
Im trying to use Rapidjson on iOS to parse map data that is in a GeoJson format. The parsing works fine for most cases but fails for some particular cases. I have noticed that the Json parsing fails when particular children elements are empty.  

For example if i try to parse the following GeoJson i get a `kParseErrorDocumentRootNotSingular` error with an error offset of 12310 and im assuming it is because certain member elements in this Json (landuse_labels.features , places.features , pois.features) are empty. 

~~~js
{
    "buildings": {
        "type": "FeatureCollection",
        "features": [
            {
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                        [
                            [
                                -71.345721,
                                41.787756
                            ],
                            [
                                -71.345661,
                                41.787846
                            ],
                            [
                                -71.345534,
                                41.787878
                            ],
                            [
                                -71.345413,
                                41.787834
                            ],
                            [
                                -71.34537,
                                41.787739
                            ],
                            [
                                -71.345429,
                                41.787649
                            ],
                            [
                                -71.345556,
                                41.787617
                            ],
                            [
                                -71.345677,
                                41.787661
                            ],
                            [
                                -71.345721,
                                41.787756
                            ]
                        ]
                    ]
                },
                "type": "Feature",
                "properties": {
                    "id": 274563682,
                    "area": 1171
                }
            }
        ]
    },
    "landuse_labels": {
        "type": "FeatureCollection",
        "features": []
    },
    "places": {
        "type": "FeatureCollection",
        "features": []
    },
    "pois": {
        "type": "FeatureCollection",
        "features": []
    },
    "water": {
        "type": "FeatureCollection",
        "features": [
            {
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                        [
                            [
                                -71.355634,
                                41.782305
                            ],
                            [
                                -71.355587,
                                41.782452
                            ],
                            [
                                -71.355456,
                                41.782564
                            ],
                            [
                                -71.354612,
                                41.782906
                            ],
                            [
                                -71.354012,
                                41.783493
                            ],
                            [
                                -71.3539,
                                41.783382
                            ],
                            [
                                -71.353947,
                                41.782948
                            ],
                            [
                                -71.354106,
                                41.782655
                            ],
                            [
                                -71.354893,
                                41.781809
                            ],
                            [
                                -71.355259,
                                41.781697
                            ],
                            [
                                -71.355456,
                                41.78169
                            ],
                            [
                                -71.355596,
                                41.782012
                            ],
                            [
                                -71.355634,
                                41.782305
                            ]
                        ]
                    ]
                },
                "type": "Feature",
                "properties": {
                    "source": "openstreetmap.org",
                    "kind": "water",
                    "id": 208859735,
                    "area": 23294
                }
            }
        ]
    },
    "roads": {
        "type": "FeatureCollection",
        "features": [
            {
                "geometry": {
                    "type": "LineString",
                    "coordinates": [
                        [
                            -71.345215,
                            41.786407
                        ],
                        [
                            -71.347176,
                            41.786438
                        ],
                        [
                            -71.348999,
                            41.785934
                        ],
                        [
                            -71.356201,
                            41.78373
                        ]
                    ]
                },
                "type": "Feature",
                "properties": {
                    "kind": "minor_road",
                    "name": "Socony Road",
                    "sort_key": 16,
                    "is_link": "no",
                    "is_tunnel": "no",
                    "is_bridge": "no",
                    "id": 92269642,
                    "highway": "service"
                }
            },
            {
                "geometry": {
                    "type": "LineString",
                    "coordinates": [
                        [
                            -71.348999,
                            41.785934
                        ],
                        [
                            -71.349228,
                            41.786022
                        ],
                        [
                            -71.349434,
                            41.786343
                        ],
                        [
                            -71.349681,
                            41.787697
                        ]
                    ]
                },
                "type": "Feature",
                "properties": {
                    "kind": "minor_road",
                    "sort_key": 16,
                    "is_link": "no",
                    "is_tunnel": "no",
                    "is_bridge": "no",
                    "id": 19351772,
                    "highway": "service"
                }
            },
            {
                "geometry": {
                    "type": "LineString",
                    "coordinates": [
                        [
                            -71.348557,
                            41.780216
                        ],
                        [
                            -71.348282,
                            41.779915
                        ],
                        [
                            -71.34773,
                            41.779505
                        ]
                    ]
                },
                "type": "Feature",
                "properties": {
                    "kind": "minor_road",
                    "sort_key": 17,
                    "is_link": "no",
                    "is_tunnel": "no",
                    "is_bridge": "no",
                    "id": 19352227,
                    "highway": "residential"
                }
            },
            {
                "geometry": {
                    "type": "LineString",
                    "coordinates": [
                        [
                            -71.35094,
                            41.779505
                        ],
                        [
                            -71.3489,
                            41.780132
                        ],
                        [
                            -71.348053,
                            41.780331
                        ],
                        [
                            -71.347382,
                            41.780384
                        ],
                        [
                            -71.345215,
                            41.78033
                        ]
                    ]
                },
                "type": "Feature",
                "properties": {
                    "kind": "minor_road",
                    "name": "Forbes Street",
                    "sort_key": 17,
                    "is_link": "no",
                    "is_tunnel": "no",
                    "is_bridge": "no",
                    "id": 278496863,
                    "highway": "residential"
                }
            },
            {
                "geometry": {
                    "type": "LineString",
                    "coordinates": [
                        [
                            -71.356201,
                            41.787685
                        ],
                        [
                            -71.355858,
                            41.78751
                        ]
                    ]
                },
                "type": "Feature",
                "properties": {
                    "kind": "minor_road",
                    "name": "Village Drive",
                    "sort_key": 17,
                    "is_link": "no",
                    "is_tunnel": "no",
                    "is_bridge": "no",
                    "id": 19369545,
                    "highway": "residential"
                }
            }
        ]
    },
    "earth": {
        "type": "FeatureCollection",
        "features": [
            {
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                        [
                            [
                                -71.345215,
                                41.779505
                            ],
                            [
                                -71.356201,
                                41.779505
                            ],
                            [
                                -71.356201,
                                41.787697
                            ],
                            [
                                -71.345215,
                                41.787697
                            ],
                            [
                                -71.345215,
                                41.779505
                            ]
                        ]
                    ]
                },
                "type": "Feature",
                "properties": {
                    "land": "base",
                    "id": 269814
                }
            }
        ]
    },
    "landuse": {
        "type": "FeatureCollection",
        "features": [
            {
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                        [
                            [
                                -71.345215,
                                41.783188
                            ],
                            [
                                -71.345753,
                                41.783583
                            ],
                            [
                                -71.345674,
                                41.784833
                            ],
                            [
                                -71.345953,
                                41.786105
                            ],
                            [
                                -71.347718,
                                41.786109
                            ],
                            [
                                -71.349014,
                                41.785746
                            ],
                            [
                                -71.349427,
                                41.786051
                            ],
                            [
                                -71.349707,
                                41.786463
                            ],
                            [
                                -71.349867,
                                41.787697
                            ],
                            [
                                -71.345215,
                                41.787697
                            ],
                            [
                                -71.345215,
                                41.783188
                            ]
                        ]
                    ]
                },
                "type": "Feature",
                "properties": {
                    "source": "openstreetmap.org",
                    "kind": "industrial",
                    "id": 274563704,
                    "area": 1633940
                }
            }
        ]
    }
}
~~~

What does `kParseErrorDocumentRootNotSingular` exactly imply? Can i resolve this error without altering the geoJson response?

**Comment by miloyip** [comment] 2015-05-29 07:40
Firstly, I cannot reproduce the error as mentioned by:

~~~cpp
const char* json = "...";
Document d;
d.Parse(json);
EXPECT_FALSE(d.HasParseError());
~~~

Secondly, `kParseErrorDocumentRootNotSingular` implys that there are multiple values at the top level. For example, these [tests](https://github.com/miloyip/rapidjson/blob/master/test/unittest/readertest.cpp#L912) generate this error:

~~~cpp
    // The document root must not follow by other values.
    TEST_ERROR(kParseErrorDocumentRootNotSingular, "[] 0");
    TEST_ERROR(kParseErrorDocumentRootNotSingular, "{} 0");
    TEST_ERROR(kParseErrorDocumentRootNotSingular, "null []");
    TEST_ERROR(kParseErrorDocumentRootNotSingular, "0 {}");
~~~

Or in other words, there are non-whitespace characters after the root value, before the end of JSON.

If there are multiple JSONs in the stream, you can add a parse flag `kParseStopWhenDoneFlag` as stated [here](http://miloyip.github.io/rapidjson/md_doc_dom.html#Parsing). And then you can continue to parse the stream for the next JSON.

Finally, I am unsure about which problem is it. You may print out the characters around the error offset to check what is the cause.

**Comment by xmarklabs** [comment] 2015-05-29 08:03
Thanks for the quick reply!

Adding the flag seemed to solve my issue.
I was doing this
doc.Parse(_in.src_)
Now i am doing this
`doc.Parse<rapidjson::kParseStopWhenDoneFlag>(_in.src_)

And the parsing error seems to have gone away!

**Comment by miloyip** [comment] 2015-05-29 08:11
But I think you should check if there are some hidden issues, for example, some invalid characters after `}` in the JSON. It may be potentially some bugs in the network/file stream or something.

Anyway, I close this issue now.

**Closed by miloyip** 2015-05-29 08:11 UTC

**Comment by xmarklabs** [comment] 2015-05-29 08:35
Will do! Thanks for your help!

**Comment by edporras** [comment] 2016-01-04 14:23
Hi,

I hope it's OK to comment here but I've ran into the same issue and this is the only reference I've found to it. My tool opens the same JSON file every time at launch, reads its contents, and attempts to parse it with rapidjson. Every 4th or 5th time, parsing fails with a `The document root must not follow by other values.` error even though I'm not modifying the file in between runs. I can replicate this every time too.

I've worked around it by what you've suggested here (`kParseStopWhenDoneFlag`) but I wonder if it's masking the real issue. My file doesn't seem to have anything following the closing curly brace of the root object (and, yes, there's a single object). It's just strange that it parses without issue 75-80% of the time.

Thanks.

**Comment by miloyip** [comment] 2016-01-05 01:33
You may show your code for reading the file. Also, you may set break point in RapidJSON (searching that flag), and check what characters left after the last `]` or `}`.

**Comment by fjhub** [comment] 2016-02-11 17:44
I recently came across an issue where I parsing multiple files and every time parsing the second file resulted in HasParseError() being true.  I thought may my JSON files were bad but I ran them through jsonlint and they were fine.  My parsing algorithm takes a variable list of files so if I parsed each file individually then things worked as expected.  After discovering #479, I added the code to print the error:
```
   The document root must not follow by other values. (2)
```
This led me here and I added the ```rapidjson::kParseStopWhenDoneFlag``` and things worked as expected when parsing multiple files.  This really didn't make sense because ```Parse()``` was called with a ```char *``` buffer which was dynamically allocated for each file.  I modified my code to isolate things so I could include it here in simplest form:
```
   char   *jsonStr;
   Document   doc0, doc1, doc2, doc3;
   rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>   &a0 = doc0.GetAllocator();
   rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>   &a1 = doc1.GetAllocator();
   rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>   &a2 = doc2.GetAllocator();
   rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>   &a3 = doc3.GetAllocator();
   doc0.SetObject();
   doc1.SetObject();
   doc2.SetObject();
   doc3.SetObject();

   jsonStr  = parseFile(f0);
   doc0.Parse(jsonStr);
   if (1) {
      ParseErrorCode   isOk = doc0.GetParseError();
       if (isOk != rapidjson::kParseErrorNone) {
         fprintf(stderr, "0 PARSE ERROR:\n");
         fprintf(stderr, "   %s (%u)\n", GetParseError_En(isOk), doc0.GetParseError());
         }
   }
   free(jsonStr);
   jsonStr  = parseFile(f1);
   doc1.Parse(jsonStr);
   if (1) {
      ParseErrorCode   isOk = doc1.GetParseError();
       if (isOk != rapidjson::kParseErrorNone) {
         fprintf(stderr, "1 PARSE ERROR:\n");
         fprintf(stderr, "   %s (%u)\n", GetParseError_En(isOk), doc1.GetParseError());
         }
   }
```

And here are the contents of the 2 files:
```
{ "nameA":"valueA", "nameB":"valueB", "NameC":"valueC", "arrA" : [ { "nameD" : "valueD", "arrB" : [ { "nameE" : "valueE" } ] }, { "nameF" : "valueF", "arrC" : [ { "nameG" : "valueG", "nameH" : "valueH" } ] } ] }
```
```
{ "arrA" : [ { "nameA" : "valueA", "arrB" : [ { "nameB" : "valueB" } ] }, { "nameC" : "valueC", "arrC" : [ { "nameD" : "valueD", "nameE" : "valueE"} ] } ] }
```
The other interesting thing I noticed was that if I specified the same file twice then things worked as expected.

Hopefully someone could shed some light on what I'm doing wrong...

thanks.

**Comment by miloyip** [comment] 2016-02-11 17:54
Have you appended '\0' in `jsonStr`?
Or you can show the `parseFile()` implementation here.

**Comment by fjhub** [comment] 2016-02-11 18:00
Yes.
In the line ```jsonStr = parseFile(f)``` the function parseFile() uses calloc() to build a dynamic string when parsing the file.

**Comment by edporras** [comment] 2016-02-11 18:04
Hi, sorry I never got back to you. Here's my code which produces the `The document root must not follow by other values` error (`read_text_file` allocates and fills `data`):

```c
               char* data;

                if (!util::fs::read_text_file(config_file, &data)) {
                    return false;
                }

                rapidjson::Document d;
                d.Parse(data);
                delete [] data;

                if (d.HasParseError()){
                    std::cerr << "Parse error reading " << config_file << ": " << GetParseError_En(d.GetParseError()) << std::endl;
                    return false;
                }
```

If I change the `d.Parse(data)` call to `d.Parse<rapidjson::kParseStopWhenDoneFlag>(data)`, the file is parsed correctly.  [Here's a simple JSON file](https://github.com/miloyip/rapidjson/files/126844/simple.txt) that reproduces this for me.

**Comment by miloyip** [comment] 2016-02-12 04:17
@fjhub Can you show the code of `parseFile()`?

**Comment by miloyip** [comment] 2016-02-12 04:17
@edporras I suspected the `data` may not be null terminated.

**Comment by fjhub** [comment] 2016-02-12 07:06
You were right.  I started to write the function here removing the extraneous code to keep it simple and before I got halfway through I saw the problem where the initial buffer was not zeroed out.  Made the change and works like a charm without the done flag.

Thanks for pointing out the issue.

**Comment by edporras** [comment] 2016-02-12 09:11
I second that. Increased the data buffer size by 1 to null-terminale it and it works now. Thank you and sorry about the delay again.

**Comment by kariya2** [comment] 2017-05-03 20:49
Hey sorry to re comment here again. I was facing the same issue. I addded the parse flag recommmended and the parsing went away. It now however fails isObject and isArray so I was wondering if you guys had any input on this

**Comment by miloyip** [comment] 2017-05-04 01:58
@kariya2 Please provide a minimal reproduction case. Probably in a new issue.
